b2wdigital/restQL-http

Dockerfile
=> Standardize Dockerfile with uppercase Docker commands

.dockerignore, Dockerfile, compose.yml
- Smaller Docker image (final size is now ~240MB)
- docker-compose example (restQL-server + mongodb)
=> Docker stuff

compose.yml, docker/nginx/upstream.conf
Use nginx to enable CORS requests (client-side libraries)
=> Add nginx to docker-compose

roadmap meetings/2018-06-27-meetingN1.md
added the correct link to the members profiles
=> refactor(markdown): added github link

src/restql/server/request_util.clj
#39 adding 'accept-encoding' to headers blacklist
=> fix(request) adding 'accept-encoding' to headers blacklist

src/clojure/restql/http/async_handler.clj, src/clojure/restql/http/request/queries.clj, test/clojure/restql/http/async_handler_test.clj, test/clojure/restql/http/request/queries_test.clj
=> fix(response): return 404 for inexistent queries

src/clojure/restql/http/async_handler.clj, test/clojure/restql/http/async_handler_test.clj
Closes [B2W-BIT/restQL-http#61]
=> Fix(response): should parse exception and return status 500

src/clojure/restql/http/async_handler.clj, src/clojure/restql/http/request_util.clj
Fixes:
- return 500 when create response throws exception;
- parse details with nested lists.
=> Fixes related to issue [#61]

test/clojure/restql/http/request_util_test.clj
=> test(parsed_query): add test ensuring that cache is used

src/clojure/restql/http/query/handler.clj, src/clojure/restql/http/query/headers.clj, src/clojure/restql/http/query/runner.clj, test/clojure/restql/http/query/handler_test.clj, test/clojure/restql/http/query/headers_test.clj
=> Multiplex when have list as query-param

src/clojure/restql/http/cache/core.clj, src/clojure/restql/http/query/mappings.clj, src/clojure/restql/http/request/queries.clj
=> chore(cache): update fetch query cache to FIFO strategy [#99]

scripts/prepare.sh
=> chore(memory): set -XX:MaxRAMPercentage=75 as default JAVA_OPTS

project.clj, src/clojure/restql/http/query/handler.clj, src/clojure/restql/http/query/runner.clj, src/clojure/restql/http/server/cors.clj, src/clojure/restql/http/server/handler.clj, src/resources/restql.sample.yml, test/clojure/restql/http/query/handler_test.clj, test/clojure/restql/http/query/runner_test.clj
Add CORS headers to restQL-HTTP response, motivated by issue #110
=> feat(CORS): Cors headers configuration

project.clj, src/clojure/restql/http/query/headers.clj, src/clojure/restql/http/query/runner.clj, test/clojure/restql/http/query/runner_test.clj
Solving issue B2W-BIT/restQL-http/issues/123
=> Error cache control header

docs/restql/config.md, docs/restql/howToDev.md, docs/restql/manager.md, docs/restql/queryLang.md, docs/restql/restqlJS.md, docs/restql/tutorial/settingUp.md
Changes made:
- Add RestQL JS to docs
- Changed references to `/src/resources/restql.yml` to `restql.yml`
- Add `Retrieving All Revisions of a Saved Query` section to Manager page
- Add  `update` (http PATCH) method to docs
=> Doc Update v3

src/clojure/restql/http/server/handler.clj
=> feat(run-query): accept any method on handlers [#136]

src/clojure/restql/http/query/calculate_response_status_code.clj, test/clojure/restql/http/query/status_code_test.clj
=> fix(query): add resource details list support

src/clojure/restql/http/query/calculate_response_status_code.clj, test/clojure/restql/http/query/status_code_test.clj
=> fix(multiplexed-calls): ignore errors when requested

docs/restql/query-language.md
=> doc(query-language): fix example

examples/api-and-manager/README.md, examples/api-and-manager/docker-compose.yml, examples/api/README.md, examples/api/restql.yml, examples/full-stack-with-nginx/README.md, examples/full-stack-with-nginx/docker-compose.yml, examples/full-stack-with-nginx/nginx/default.conf
=> chore(examples): add new examples to run restql with docker and compose

src/clojure/restql/http/query/handler.clj, src/clojure/restql/http/query/runner.clj, test/clojure/restql/http/query/handler_test.clj
=> fix(query): expose query parse to use on parse handler [#168]

src/clojure/restql/http/database/persistence.clj
Sorry if this is too nit picky...
Just trying to help
=> corrected spelling for "skipping", tense for "set" in line 14

docs/index.html
This pull request fix sidebar logo
=> Fix sidebar logo in documentation
